# Loading packages
library(stringr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(tibble)
library(forcats)
library(readxl)
library(flextable)
library(officer)
library(janitor)
library(grid)
library(gridExtra)
library(noradplot)
library(nombre)
library(glue)
library(here)
library(readr)
library(scales)
library(rlang)

noradplot::ggnorad()